name: 01 - Building Blocks

on: push

jobs: 
    ech0-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run:  echo "Hello, World!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Failes step
              run: |
                echo "I will fail"
                exit 1
            - name: Say goodbye
              run: echo "Goodbye!"  


