name: 15 matrices workflow
on: 
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false 
      matrix:
        node-version: [18, 20, 21]
        os:
          - ubuntu-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with: ${{ matrix.node-version }}
    - name: Perform some tests
      run: echo "Running tests on OS ${{ matrix.os}} and NodeJS ${{ matrix.node-version }}"
